import { SyncState, ActivityItem, TestSuiteResult, IssueItem, FixPatch } from '../types';
import { AIOrchestrator } from './aiOrchestrator';
import { DemoTestRunner } from '../demo-repo/demoRunner';

export type SyncEventListener = (event: string, data: any) => void;

export class SyncService {
  private static instance: SyncService;
  private ws: WebSocket | null = null;
  private listeners: Set<SyncEventListener> = new Set();
  
  private state: SyncState = {
    isPhoneConnected: true,
    phoneDeviceModel: 'iQOO 13 Pro 5G',
    isLaptopConnected: true,
    laptopName: 'MacBook Pro M3 Max (Dev Server)',
    isGitHubConnected: true,
    aiRuntime: 'laptop-connected',
    lastCommandReceived: undefined,
    isDemoMode: true,
  };

  private isFixApplied: boolean = false;
  private activityLog: ActivityItem[] = [
    { id: 'act_1', timestamp: '14:20:05', type: 'connect', title: 'iQOO 13 Pro Connected', description: 'Established secure WebSocket session with laptop execution node.', status: 'success' },
    { id: 'act_2', timestamp: '14:20:10', type: 'index', title: 'Repository Codebase Indexed', description: '248 files processed. Dependency graph & AST symbols generated for codeorbit-demo.', status: 'success' },
  ];

  private constructor() {
    this.connectWebSocket();
  }

  public static getInstance(): SyncService {
    if (!SyncService.instance) {
      SyncService.instance = new SyncService();
    }
    return SyncService.instance;
  }

  private connectWebSocket() {
    try {
      const wsUrl = `ws://${window.location.hostname}:3001`;
      this.ws = new WebSocket(wsUrl);

      this.ws.onopen = () => {
        console.log('⚡ Connected to CodeOrbit Laptop WebSocket Sync Server');
        this.state.isLaptopConnected = true;
        this.emit('STATE_CHANGE', this.state);
      };

      this.ws.onmessage = (evt) => {
        try {
          const payload = JSON.parse(evt.data);
          this.emit(payload.event, payload.data);
        } catch (e) {
          console.error('WS Parse Error', e);
        }
      };

      this.ws.onerror = () => {
        console.log('WS Connection fallback to local event bus');
      };
    } catch (e) {
      console.log('WS fallback active');
    }
  }

  public addListener(listener: SyncEventListener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emit(event: string, data: any) {
    this.listeners.forEach((listener) => listener(event, data));
  }

  public getSyncState(): SyncState {
    return { ...this.state };
  }

  public getActivityLog(): ActivityItem[] {
    return [...this.activityLog];
  }

  public addActivity(item: Omit<ActivityItem, 'id' | 'timestamp'>) {
    const newItem: ActivityItem = {
      ...item,
      id: `act_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      timestamp: new Date().toLocaleTimeString(),
    };
    this.activityLog = [newItem, ...this.activityLog];
    this.emit('ACTIVITY_UPDATED', this.activityLog);
  }

  // Action Dispatchers for Mobile & Desktop
  public async scanErrorFromCamera(ocrText?: string): Promise<IssueItem> {
    this.state.lastCommandReceived = 'SCAN_ERROR';
    this.addActivity({
      type: 'scan',
      title: 'Camera Error Scan Triggered',
      description: ocrText ? `OCR captured: "${ocrText.substring(0, 45)}..."` : 'iQOO Vision OCR scanned error from laptop screen.',
      status: 'progress'
    });
    this.emit('PHONE_COMMAND', { action: 'SCAN_ERROR' });

    const issue = AIOrchestrator.getDemoIssue();

    setTimeout(() => {
      this.addActivity({
        type: 'root-cause',
        title: 'Root Cause Identified (94% Confidence)',
        description: `Pinpointed in ${issue.filePath}:${issue.lineNumber} - Null pointer exception during token parsing.`,
        status: 'warning'
      });
      this.emit('ROOT_CAUSE_FOUND', issue.rootCause);
    }, 1200);

    return issue;
  }

  public async generateFix(): Promise<FixPatch> {
    this.state.lastCommandReceived = 'GENERATE_FIX';
    this.addActivity({
      type: 'patch',
      title: 'Fix Patch Generated by AI Fix Agent',
      description: 'Created safe git worktree patch for src/middleware/authMiddleware.ts',
      status: 'progress'
    });

    const issue = AIOrchestrator.getDemoIssue();
    this.isFixApplied = true;

    setTimeout(() => {
      this.addActivity({
        type: 'patch',
        title: 'Patch Applied to Sandbox Workspace',
        description: 'Successfully modified authMiddleware.ts in isolated dev workspace.',
        status: 'success'
      });
      this.emit('PATCH_APPLIED', issue.patch);
    }, 1000);

    return issue.patch!;
  }

  public async runTestExecution(onProgress?: (percent: number, statusText: string) => void): Promise<TestSuiteResult> {
    this.state.lastCommandReceived = 'RUN_TESTS';
    this.addActivity({
      type: 'test',
      title: 'Laptop Test Execution Initiated',
      description: 'Command sent from iQOO phone. Running 17 unit & integration tests...',
      status: 'progress'
    });

    if (onProgress) onProgress(15, 'Initializing test runner environment...');

    await new Promise((r) => setTimeout(r, 600));
    if (onProgress) onProgress(45, 'Executing auth.test.ts...');

    await new Promise((r) => setTimeout(r, 700));
    if (onProgress) onProgress(80, 'Executing payment.test.ts & security.test.ts...');

    await new Promise((r) => setTimeout(r, 800));
    if (onProgress) onProgress(100, 'Test suite run completed!');

    const results = DemoTestRunner.runTests(this.isFixApplied);

    if (results.failed === 0) {
      this.addActivity({
        type: 'test',
        title: '✓ FIX VERIFIED (17 / 17 Passed)',
        description: 'All 17 tests passed successfully. Code changes safe to merge.',
        status: 'success'
      });
    } else {
      this.addActivity({
        type: 'test',
        title: `Tests Failed (${results.failed} Failures)`,
        description: `${results.failed} tests failing due to auth middleware null pointer exception.`,
        status: 'warning'
      });
    }

    this.emit('TEST_COMPLETED', results);
    return results;
  }

  public isFixCurrentlyApplied(): boolean {
    return this.isFixApplied;
  }
}
